# Description: This workflow triggers when a comment is made on an issue.
# It checks for specific slash commands in the comment body to determine whether to merge or close the associated pull request.
name: 'Merge and close PR using slash-commands'
on: 
  issue_comment:

permissions: write-all
  
env:
  EVENT_CHECK_VARIABLE: 'slash'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.issue.number }} 
  REPO_NAME: ${{ github.repository }}
  MERGE_PR: ${{ github.event.comment.body == '/Approved' }}
  CLOSE_PR: ${{ github.event.comment.body == '/Close' }}
  WEBHOOK: ${{ secrets.GCHAT_WEBHOOK_URL}}
  EVENT: ${{ github.event.action }} 
  
jobs:
  Merge_and_Close-PR:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Merge and close PR
        uses: rajmalasoni/CHATOPSTEST@2.5.0.0